In [1]:
from bs4 import BeautifulSoup
import pandas as pd
from transformers import AutoConfig
import glob

In [2]:
from vllm import LLM, SamplingParams

In [3]:
# Initialize the model

model = LLM("/mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/",
    tensor_parallel_size=4, #change it to number of GPU
    max_model_len=5000,
    swap_space=0,
    gpu_memory_utilization = 0.95,
    trust_remote_code=False
)

INFO 06-05 22:09:13 config.py:905] Defaulting to use mp for distributed inference
INFO 06-05 22:09:19 llm_engine.py:237] Initializing an LLM engine (v0.6.3.post1) with config: model='/mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/', speculative_config=None, tokenizer='/mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=5000, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
INFO 06-05 22:09:20 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273175) (VllmWorkerProcess pid=2273176) INFO 06-05 22:09:21 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 06-05 22:09:21 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 06-05 22:09:21 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 06-05 22:09:25 utils.py:1008] Found nccl from library libnccl.so.2
INFO 06-05 22:09:25 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=2273175) (VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273176) INFO 06-05 22:09:25 utils.py:1008] Found nccl from library libnccl.so.2
INFO 06-05 22:09:25 utils.py:1008] Found nccl from library libnccl.so.2
INFO 06-05 22:09:25 utils.py:1008] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273175) (VllmWorkerProcess pid=2273176) INFO 06-05 22:09:25 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 06-05 22:09:25 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 06-05 22:09:25 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 06-05 22:09:36 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /home/wangp5/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
(VllmWorkerProcess pid=2273175) (VllmWorkerProcess pid=2273176) (VllmWorkerProcess pid=2273177) INFO 06-05 22:09:36 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /home/wangp5/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
INFO 06-05 22:09:36 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /home/wangp5/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
INFO 06-05 22:09:36 custom_all_reduce_utils.py:242] reading GPU P2P access cache from /home/wangp5/.cache/vllm/gpu_p2p_access_cache_for_0,1,2,3.json
INFO 06-05 22:09:36 shm_broadcast.py:241] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x15542f0092a0>, local_subscribe_port=46761, remote_subscribe_port=None)
INFO 06-05 22:09:36 model_runner.py:1056] Starting to load model /mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/...
(VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273176) (VllmWorkerProcess pid=2273175) INFO 06-05 22:09:36 model_runner.py:1056] Starting to load model /mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/...
INFO 06-05 22:09:36 model_runner.py:1056] Starting to load model /mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/...
INFO 06-05 22:09:36 model_runner.py:1056] Starting to load model /mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct/...

Loading safetensors checkpoint shards:   0% Completed | 0/30 [00:00<?, ?it/s]

INFO 06-05 22:16:16 model_runner.py:1067] Loading model weights took 32.8892 GB
(VllmWorkerProcess pid=2273175) (VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273176) INFO 06-05 22:16:16 model_runner.py:1067] Loading model weights took 32.8892 GB
INFO 06-05 22:16:16 model_runner.py:1067] Loading model weights took 32.8892 GB
INFO 06-05 22:16:16 model_runner.py:1067] Loading model weights took 32.8892 GB
INFO 06-05 22:16:24 distributed_gpu_executor.py:57] # GPU blocks: 766, # CPU blocks: 0
INFO 06-05 22:16:24 distributed_gpu_executor.py:61] Maximum concurrency for 5000 tokens per request: 2.45x
INFO 06-05 22:16:24 model_runner.py:1395] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-05 22:16:24 model_runner.py:1399] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273176) (VllmWorkerProcess pid=2273175) INFO 06-05 22:16:24 model_runner.py:1395] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-05 22:16:24 model_runner.py:1395] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-05 22:16:24 model_runner.py:1395] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273175) (VllmWorkerProcess pid=2273176) INFO 06-05 22:16:24 model_runner.py:1399] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-05 22:16:24 model_runner.py:1399] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-05 22:16:24 model_runner.py:1399] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-05 22:17:43 custom_all_reduce.py:233] Registering 5635 cuda graph addresses
(VllmWorkerProcess pid=2273176) (VllmWorkerProcess pid=2273177) INFO 06-05 22:17:43 model_runner.py:1523] Graph capturing finished in 80 secs.
INFO 06-05 22:17:43 custom_all_reduce.py:233] Registering 5635 cuda graph addresses
(VllmWorkerProcess pid=2273175) INFO 06-05 22:17:43 custom_all_reduce.py:233] Registering 5635 cuda graph addresses
INFO 06-05 22:17:43 custom_all_reduce.py:233] Registering 5635 cuda graph addresses
(VllmWorkerProcess pid=2273177) (VllmWorkerProcess pid=2273176) (VllmWorkerProcess pid=2273175) INFO 06-05 22:17:43 model_runner.py:1523] Graph capturing finished in 80 secs.
INFO 06-05 22:17:43 model_runner.py:1523] Graph capturing finished in 80 secs.
INFO 06-05 22:17:43 model_runner.py:1523] Graph capturing finished in 80 secs.

In [6]:
import re
import os
# Load train corpus 
with open('../../LLM/tmVar/tmVarCorpus/train.PubTator.txt', 'r') as file:
    corpus = file.read()
# Regular expression to match PubMed ID and the section after "|a|"
pattern = r'(\d+)\|a\|([^\n]+)'
# Find all matches
matches = re.findall(pattern, corpus)
parsed_dict = {match[0]: match[1].strip() for match in matches}

tmvar_corpus=[]
pmid_list=[]
for pubmed_id, abstract in parsed_dict.items():
    pmid_list.append(pubmed_id)
    tmvar_corpus.append(f"Abstract: {abstract}\n")
    #print(f"PubMed ID: {pubmed_id}\nAbstract: {abstract}\n")

# Load test corpus
with open('../../LLM/tmVar/tmVarCorpus/test.PubTator.txt', 'r') as file:
    corpus = file.read()
    
matches2 = re.findall(pattern, corpus)
parsed_dict2 = {match[0]: match[1].strip() for match in matches2}

for pubmed_id, abstract in parsed_dict2.items():
    pmid_list.append(pubmed_id)
    tmvar_corpus.append(f"Abstract: {abstract}\n")
    #print(f"PubMed ID: {pubmed_id}\nAbstract: {abstract}\n")

In [7]:
len(tmvar_corpus)

500

In [9]:
tmvar_corpus[0]

'Abstract: Factor XI (FXI) deficiency is a rare autosomal recessive coagulation disorder most commonly found in Ashkenazi and Iraqi Jews, but it is also found in other ethnic groups. It is a trauma or surgery-related bleeding disorder, but spontaneous bleeding is rarely seen. The clinical manifestation of bleeding in FXI deficiency cases is variable and seems to poorly correlate with plasma FXI levels. The molecular pathology of FXI deficiency is mutation in the F11 gene on the chromosome band 4q35. We report a novel mutation of the F11 gene in an 18-year-old asymptomatic Korean woman with mild FXI deficiency. Pre-operative laboratory screen tests for lipoma on her back revealed slightly prolonged activated partial thromboplastin time (45.2 sec; reference range, 23.2-39.4 sec). Her FXI activity (35%) was slightly lower than the normal FXI activity (reference range, 50-150%). Direct sequence analysis of the F11 gene revealed a heterozygous A to G substitution in nucleotide 1517 (c.1517A>G) of exon 13, resulting in the substitution of aspartic acid with glycine in codon 506 (p.Asp506Gly). To the best of our knowledge, the Asp506Gly is a novel missense mutation, and this is the first genetically confirmed case of mild FXI deficiency in Korea.\n'

In [10]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("/mnt/isilon/wang_lab/shared/Llama3_3/Llama-3.3-70B-Instruct")

In [16]:
def generate_prompt(tmvar_corpus, type_of_prompt):
    '''
    type_of_prompt:'zeroshot_prompt', 'cot_para_prompt', 'para_cot_prompt', 'fewshot_prompt', 'cot_fewshot_prompt'
    '''
    prompts= []
    for paragraph in tmvar_corpus:
        # Combine CoT prompt with the actual paragraph
        if type_of_prompt=='zeroshot_prompt':
            prompt=f'{zero_shot_prompt}\nParagraph: \"{paragraph}\"'
        elif type_of_prompt=='cot_para_prompt':
            prompt=f'{cot_prompt_final}\nParagraph: \"{paragraph}\"'
        elif type_of_prompt=='para_cot_prompt':
            prompt=f'Paragraph: \"{paragraph}\"\n{cot_prompt_final}'
        elif type_of_prompt=='fewshot_prompt':
            prompt=f'{few_shot_examples}\nParagraph: \"{paragraph}\"'
        elif type_of_prompt=='cot_fewshot_prompt':
            prompt=f'{cot_prompt_final}\n{few_shot_examples}\nParagraph: \"{paragraph}\"'

        #short system prompt
        messages = [
            {'role': 'system', 'content': 
             """You are an expert in genomics and bioinformatics. Extract the variant-related information from scientific publication paragraphs."""},
            {'role': 'user', 'content': prompt},  # Instruction (CoT)
        ]

        # Apply chat template
        templated_prompt = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,  # Adds necessary tokens for generation
            tokenize=False               # Returns a string
        )

        templated_prompt=templated_prompt.replace('Cutting Knowledge Date: December 2023\nToday Date: 26 Jul 2024\n\n','')
        prompts.append(templated_prompt)
    
    return prompts

In [29]:
# Chain of Thought (CoT) Prompt
cot_prompt_final = """
Extract the information of gene, DNA mutation, protein mutation, related disease, experiment result, and pathogenicity from this research paper paragraph in the format of ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity.

Follow these steps to ensure accuracy:
1. Identify Relevant Genes and Mutations, locate any gene names or symbols mentioned in the paper.
2. Identify if there is any DNA-level mutation. Make sure the DNA mutation only contains letter A,T,C,G. Note any variant start with 'c.'.
3. Identify if there is any protein-level mutation. Note different expression of a protein or amino acid, no matter in three letter or one letter. If only an RSID is found, fill it in as the DNA mutation. Note any variant start with 'p.'.
4. Determine Disease Association: identify any diseases or conditions related to each gene and mutation. Look for terms like "disease," "syndrome," "condition," or names of specific conditions.
5. Extract Functional or Experimental Result: find statements describing the effect of each mutation, especially in terms of experimental assays or functional impacts. Note results like "rescued" or "failed to rescue" a function.
6. Assign Pathogenicity Level: determine if the mutation is "pathogenic," "benign," or similar terms indicating pathogenicity or clinical relevance.
7. Format Output Concisely: present the result in this format: ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity.

Using these steps, extract and present the unique ##gene, DNA mutation, protein mutation, disease, experiment result, pathogenicity for each mutation-disease relationship in this research paper paragraph/abstract:
"""
cot_prompt = """Extract the information of gene, DNA mutation, protein mutation, related disease, experiment result, and pathogenicity from this research paper paragraph in the format of ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity. Follow these steps to ensure accuracy:

1. Identify Relevant Genes and Mutations, locate any gene names or symbols mentioned in the paper.
2. Identify if there is any DNA-level mutation. Make sure the DNA mutation only contains letter A,T,C,G. Note any variant start with 'c.'. 
3. Identify if there is any protein-level mutation. Note different expression of a protein or amino acid, no matter in three letter or one letter. If only a RSID is found, fill it in as the DNA mutation. Note any variant start with 'p.'. 
4. Determine Disease Association: identify any diseases or conditions related to each gene and mutation. Look for terms like "disease," "syndrome," "condition," or names of specific conditions.
5. Extract Functional or Experimental Result: find statements describing the effect of each mutation, especially in terms of experimental assays or functional impacts. Note results like "rescued" or "failed to rescue" a function.
6. Assign Pathogenicity Level: determine if the mutation is "pathogenic," "benign," or similar terms indicating pathogenicity or clinical relevance.
7. Format Output Concisely: present the result in this format: ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity

Using these steps, extract and present the unique ##gene, DNA mutation, protein mutation, disease, experiment result, pathogenicity for each mutation-disease relationship in this research paper only once. Stop respond when you find all mutations.
"""
cot_instruction = """
Extract gene, DNA mutation, protein mutation, disease, experimental result, and pathogenicity from the paragraph. Follow these steps:
1. Identify genes and mutations (DNA with A, T, C, G, e.g., 'c.123A>T', protein with amino acids like 'p.Glu6Val').
2. Note associated diseases and functional results.
3. Assign pathogenicity (e.g., 'pathogenic', 'benign').
4. Format: ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity.
"""
few_shot_examples = """
Extract the information of gene, DNA mutation, protein mutation, related disease, experiment result, and pathogenicity from this research paper paragraph. Answer exactly in the format of ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity.

Example 1:
Paragraph: "Paragraph: For ESRP2, variants R250Q, R353Q and R667C rescued the molecular splicing of Arhgef11 in the Py2T assay, (Fig. 3E, Table 1)."
Output: 
##ESRP2, -, R250Q, orofacial cleft (OFC), rescued the molecular splicing of Arhgef11 in the Py2T assay, benign
##ESRP2, -, R353Q, orofacial cleft (OFC), rescued the molecular splicing of Arhgef11 in the Py2T assay, benign
##ESRP2, -, R667C, orofacial cleft (OFC), rescued the molecular splicing of Arhgef11 in the Py2T assay, benign

Example 2:
Paragraph: "The mutation c.123A>T in BRCA1 leads to a truncated protein p.Lys41*, associated with breast cancer. Functional assays showed loss of DNA repair function, indicating pathogenicity."
Output: 
##BRCA1, c.123A>T, p.Lys41*, breast cancer, loss of DNA repair function, pathogenic

Example 3:
Paragraph: "A variant in CFTR, p.Phe508del, causes cystic fibrosis. Studies confirmed defective chloride channels, confirming pathogenicity."
Output: 
##CFTR, -, p.Phe508del, cystic fibrosis, defective chloride channels, pathogenic
"""
zero_shot_prompt="""
Extract the information of gene, DNA mutation, protein mutation, related disease, experiment result, and pathogenicity from this research paper paragraph in the format of ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity.
"""

# Loop over the paragraphs
zeroshot_prompts = generate_prompt(tmvar_corpus,"zeroshot_prompt")
cot_para_prompts = generate_prompt(tmvar_corpus,"cot_para_prompt")
para_cot_prompts = generate_prompt(tmvar_corpus,"para_cot_prompt")
fewshot_prompts = generate_prompt(tmvar_corpus,"fewshot_prompt")
cot_fewshot_prompts = generate_prompt(tmvar_corpus,"cot_fewshot_prompt")

# Example output
print(zeroshot_prompts[0])

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

You are an expert in genomics and bioinformatics. Extract the variant-related information from scientific publication paragraphs.<|eot_id|><|start_header_id|>user<|end_header_id|>

Extract the information of gene, DNA mutation, protein mutation, related disease, experiment result, and pathogenicity from this research paper paragraph in the format of ##gene, DNA mutation, protein mutation, disease, experimental result, pathogenicity.

Paragraph: "Abstract: Factor XI (FXI) deficiency is a rare autosomal recessive coagulation disorder most commonly found in Ashkenazi and Iraqi Jews, but it is also found in other ethnic groups. It is a trauma or surgery-related bleeding disorder, but spontaneous bleeding is rarely seen. The clinical manifestation of bleeding in FXI deficiency cases is variable and seems to poorly correlate with plasma FXI levels. The molecular pathology of FXI deficiency is mutation in the F11 gene on the chromosome band 4q35. We report a novel mutation of the F11 gene in an 18-year-old asymptomatic Korean woman with mild FXI deficiency. Pre-operative laboratory screen tests for lipoma on her back revealed slightly prolonged activated partial thromboplastin time (45.2 sec; reference range, 23.2-39.4 sec). Her FXI activity (35%) was slightly lower than the normal FXI activity (reference range, 50-150%). Direct sequence analysis of the F11 gene revealed a heterozygous A to G substitution in nucleotide 1517 (c.1517A>G) of exon 13, resulting in the substitution of aspartic acid with glycine in codon 506 (p.Asp506Gly). To the best of our knowledge, the Asp506Gly is a novel missense mutation, and this is the first genetically confirmed case of mild FXI deficiency in Korea.
"<|eot_id|><|start_header_id|>assistant<|end_header_id|>

In [30]:
query_test=fewshot_prompts

### This controls the sampling paramters of the model. Temperature coresponse to how "creative" the model's output should be
sampling_params = SamplingParams(temperature=0.6, #0.7
                                 top_p=0.3, #0.3#use lower value to let model stick to the original text
                                 max_tokens=1000)

#The model's generate method accepts a list of strings:
output_test = model.generate(query_test,
                        sampling_params)

# Initialize an empty list to hold the rows
rows = []
i=0

# Process each line in the output
for x in output_test:

    for line in x.outputs[0].text.strip().splitlines():
        if line.startswith("##"):  # Check if the line starts with '##'
            # Remove the leading '##' and split by comma
            parts = line[2:].split(", ") #use ', ' for old prompt
            rows.append([pmid_list[i]]+parts)
    i+=1

df_cot = pd.DataFrame(rows)
df_cot=df_cot.iloc[:,:7]
df_cot.columns=['PMID','gene', 'DNA mutation', 'protein mutation', 'disease', 'experiment result', 'pathogenicity']

# get the tmVar result, to check the mutation extraction
with open('../../LLM/tmVar/tmVarCorpus/train.PubTator.txt', 'r') as file:
    corpus = file.readlines()

# Regular expression to identify rows starting with a PubMed ID followed by tab-separated values
pattern = r'^\d+\t.+'

# Filter rows matching the pattern
table_rows = [line.strip() for line in corpus if re.match(pattern, line)]
data = [row.split('\t') for row in table_rows]
df1 = pd.DataFrame(data)

# get the tmVar result for test corpus
with open('../../LLM/tmVar/tmVarCorpus/test.PubTator.txt', 'r') as file:
    corpus = file.readlines()

table_rows = [line.strip() for line in corpus if re.match(pattern, line)]
data = [row.split('\t') for row in table_rows]
df2 = pd.DataFrame(data)

#combine train and test
df = pd.concat([df1,df2], ignore_index=True, sort=False)

df_tmVar=df[[0,3,4]]
df_tmVar.columns=['PMID','Mutation','Type']

df_tmVar_dna=df_tmVar[df_tmVar['Type']=='DNAMutation']
df_tmVar_pro=df_tmVar[df_tmVar['Type']=='ProteinMutation']
df_cot=df_cot.drop_duplicates()
df_cot=df_cot[(df_cot['DNA mutation'].str.contains(r'\d', na=False)) |
      (df_cot['protein mutation'].str.contains(r'\d', na=False))] #show the rows that it has number

df_cot_dna=df_cot[['PMID','DNA mutation']].drop_duplicates()
df_cot_pro=df_cot[['PMID','protein mutation']].drop_duplicates()


#####DNA#####
df_cot_dna['DNA mutation']=df_cot_dna['DNA mutation'].apply(lambda x: x[2:] if x[:2]=='c.'else x)
df_tmVar_dna.loc[:,'Mutation']=df_tmVar_dna['Mutation'].apply(lambda x: x[2:] if x[:2]==r'c.'else x)
df_cot_dna=df_cot_dna[df_cot_dna['DNA mutation'].str.contains(r'\d', na=False)]
df_tmVar_dna=df_tmVar_dna[df_tmVar_dna['Mutation'].str.contains(r'\d', na=False)]
#remove the space, _, () for better comparison
df_cot_dna['DNA mutation']=df_cot_dna['DNA mutation'].str.replace(r"[ _()-]", "", regex=True)
df_tmVar_dna['Mutation']=df_tmVar_dna['Mutation'].str.replace(r"[ _()-]", "", regex=True)
df_cot_dna['DNA mutation']=df_cot_dna['DNA mutation'].str.replace(r"incDNA", "", regex=True)
df_cot_dna['DNA mutation']=df_cot_dna['DNA mutation'].str.replace(r"by", "", regex=True)
df_cot_dna['DNA mutation']=df_cot_dna['DNA mutation'].str.replace(r"promoter", "", regex=True)
df_tmVar_dna['Mutation']=df_tmVar_dna['Mutation'].str.replace(r"promoter", "", regex=True)
df_tmVar_dna['Mutation']=df_tmVar_dna['Mutation'].str.replace(r"by", "", regex=True)
df_tmVar_dna['Mutation']=df_tmVar_dna['Mutation'].str.replace(r"incDNA", "", regex=True)

Processed prompts:  67%|██████▋   | 337/500 [04:09<01:19,  2.06it/s, est. speed input: 1028.07 toks/s, output: 152.87 toks/s]

WARNING 06-05 22:54:20 scheduler.py:1483] Sequence group 1350 is preempted by PreemptionMode.RECOMPUTE mode because there is not enough KV cache space. This can affect the end-to-end performance. Increase gpu_memory_utilization or tensor_parallel_size to provide more KV cache memory. total_num_cumulative_preemption=101

Processed prompts: 100%|██████████| 500/500 [06:29<00:00,  1.28it/s, est. speed input: 972.76 toks/s, output: 157.03 toks/s]

In [42]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [34]:
# DNA
# Group mutations by PMID in both DataFrames
tmVar_grouped = df_tmVar_dna.groupby('PMID')['Mutation'].apply(set).reset_index(name='tmVar_Mutations')
cot_grouped = df_cot_dna.groupby('PMID')['DNA mutation'].apply(set).reset_index(name='cot_Mutations')

# Merge the two grouped DataFrames on PMID
merged = pd.merge(tmVar_grouped, cot_grouped, on='PMID', how='outer')

# Calculate the number of matches and total mutations
'''merged['Matched'] = merged.apply(
    lambda row: len(row['tmVar_Mutations'] & row['cot_Mutations']) if pd.notnull(row['tmVar_Mutations']) and pd.notnull(row['cot_Mutations']) else 0,
    axis=1
)'''
#consider true if the tm_var is a substring of cot_mut
##e.g., 'G/C' in tmVar vs. 'G/C polymorphism at position 135' in pmc-llm
##sometimes the LLM result is better than the tmVar, like the example show above
merged['Matched'] = merged.apply(
    lambda row: sum(
        any(tm_var in cot_mut for cot_mut in row['cot_Mutations']) 
        for tm_var in row['tmVar_Mutations']
    ) if pd.notnull(row['tmVar_Mutations']) and pd.notnull(row['cot_Mutations']) else 0,
    axis=1
)
merged['Total_tmVar'] = merged['tmVar_Mutations'].apply(lambda x: len(x) if pd.notnull(x) else 0)
merged['Total_cot'] = merged['cot_Mutations'].apply(lambda x: len(x) if pd.notnull(x) else 0)

# Drop unnecessary columns if desired
result = merged[['PMID', 'Matched', 'Total_tmVar', 'Total_cot']]

# Display the result
#print(result)
print('##Num of Matched, Num of tmVar result, Accuracy of LLM extraction of DNA mutation: ',
      result.sum()['Matched'],
      result.sum()['Total_tmVar'],
      result.sum()['Matched']/result.sum()['Total_tmVar'])

##Num of Matched, Num of tmVar result, Accuracy of LLM extraction of DNA mutation:  383 438 0.8744292237442922

In [36]:
merged_dna = merged

In [37]:
merged_dna.to_csv('few_shot_benchmark.tsv',sep='\t')

In [43]:
#######protein
#format the amino acid code
# provide 3 letter aa to 1 letter
one_to_three_letter_map = {
    'A': 'ALA', 'R': 'ARG', 'N': 'ASN', 'D': 'ASP',
    'C': 'CYS', 'E': 'GLU', 'Q': 'GLN', 'G': 'GLY',
    'H': 'HIS', 'I': 'ILE', 'L': 'LEU', 'K': 'LYS',
    'M': 'MET', 'F': 'PHE', 'P': 'PRO', 'S': 'SER',
    'T': 'THR', 'W': 'TRP', 'Y': 'TYR', 'V': 'VAL'
}

new_three_to_one_letter_map = {v.capitalize(): k for k, v in one_to_three_letter_map.items()}

df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].astype(str)
df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].apply(lambda x: x[2:] if x[:2]=='p.'else x)
df_tmVar_pro.loc[:, 'Mutation']=df_tmVar_pro['Mutation'].apply(lambda x: x[2:] if x[:2]==r'p.'else x)
df_cot_pro=df_cot_pro[df_cot_pro['protein mutation'].str.contains(r'\d', na=False)]
df_tmVar_pro=df_tmVar_pro[df_tmVar_pro['Mutation'].str.contains(r'\d', na=False)]

#turn 3 letter into 1 letter (not the opposite because there will be issue for words with a upper letter)
# Function to replace three-letter codes with one-letter codes in a string
def replace_amino_acids(text):
    def replace_match(match):
        return new_three_to_one_letter_map.get(match.group(0), match.group(0))

    # Replace three-letter amino acid codes found in the string
    # should allow wrong upper/lower case spelling, e.g., {R753Q, R753GLn}	{R753Q}
    return re.sub(r'[A-Za-z]{3}', replace_match, text)

df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].apply(replace_amino_acids)
df_tmVar_pro['Mutation']=df_tmVar_pro['Mutation'].apply(replace_amino_acids)

#remove the space, _, () for better comparison
df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].str.replace(r"[ _()-]", "", regex=True)
df_tmVar_pro['Mutation']=df_tmVar_pro['Mutation'].str.replace(r"[ _()-]", "", regex=True)
#remove the 'to', 'by' and replace 'stop' as '*'
df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].str.replace(r"to", "", regex=True)
df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].str.replace(r"stop", "*", regex=True)
df_cot_pro['protein mutation']=df_cot_pro['protein mutation'].str.replace(r"by", "", regex=True)
df_tmVar_pro['Mutation']=df_tmVar_pro['Mutation'].str.replace(r"by", "", regex=True)
df_tmVar_pro['Mutation']=df_tmVar_pro['Mutation'].str.replace(r"to", "", regex=True)
df_tmVar_pro['Mutation']=df_tmVar_pro['Mutation'].str.replace(r"stop", "*", regex=True)


# protein
# Group mutations by PMID in both DataFrames
tmVar_grouped = df_tmVar_pro.groupby('PMID')['Mutation'].apply(set).reset_index(name='tmVar_Mutations')
cot_grouped = df_cot_pro.groupby('PMID')['protein mutation'].apply(set).reset_index(name='cot_Mutations')

# Merge the two grouped DataFrames on PMID
merged = pd.merge(tmVar_grouped, cot_grouped, on='PMID', how='outer')

# Calculate the number of matches and total mutations
'''merged['Matched'] = merged.apply(
    lambda row: len(row['tmVar_Mutations'] & row['cot_Mutations']) if pd.notnull(row['tmVar_Mutations']) and pd.notnull(row['cot_Mutations']) else 0,
    axis=1
)'''
merged['Matched'] = merged.apply(
    lambda row: sum(
        any(str(tm_var) in str(cot_mut) for cot_mut in row['cot_Mutations']) 
        for tm_var in row['tmVar_Mutations']
    ) if pd.notnull(row['tmVar_Mutations']) and pd.notnull(row['cot_Mutations']) else 0,
    axis=1
)
merged['Total_tmVar'] = merged['tmVar_Mutations'].apply(lambda x: len(x) if pd.notnull(x) else 0)
merged['Total_cot'] = merged['cot_Mutations'].apply(lambda x: len(x) if pd.notnull(x) else 0)

# Drop unnecessary columns if desired
result = merged[['PMID', 'Matched', 'Total_tmVar', 'Total_cot']]

# Display the result
#print(result)
print('##Num of Matched, Num of tmVar result, Accuracy of LLM extraction of protein mutation: ',
      result.sum()['Matched'],
      result.sum()['Total_tmVar'],
      result.sum()['Matched']/result.sum()['Total_tmVar'])

##Num of Matched, Num of tmVar result, Accuracy of LLM extraction of protein mutation:  328 376 0.8723404255319149

In [40]:
merged_protein = merged

In [41]:
merged_protein.to_csv('few_shot_benchmark.protein.tsv',sep='\t')

In [45]:
merged_dna[merged_dna['Total_tmVar']>merged_dna['Matched']]

,PMID,tmVar_Mutations,cot_Mutations,Matched,Total_tmVar,Total_cot
8,12701064,{TAC>AAatcodon329},"{1basedeletionatcodon329TAC>AA, 3basedeletionTCC}",0,1,2
13,12737948,"{IVS10+1,g>t, 251G, IVS348C, IVS123T}","{IVS348C, IVS10+1, 251G, IVS123T}",3,4,4
15,12752111,"{IVSI129A>C, IVSI1G>A, IVSI5G>C, codonCD26GAG>GAA}","{IVSI5G>C, alpha4.2deletion, IVSI129A>C, 13bpdeletionCD6toCD10, alpha3.7deletion, CD26GAG>GAA, CD55A, IVSI1G>A}",3,4,8
27,14510914,{del439443},{13141328delins15nt},0,1,1
37,14722925,"{87+1G>A, G>Asubstitutionatnucleotide+1ofintron2, 27delC}","{N34S, 87+1G>A, 27delC}",2,3,3
39,14751036,"{2068G>C, 9+1G>T, 1242G>T, 2084G>A, 1780C>A}","{GGCCinsertionatexon8, Cinsertioninexon14betweenpositions25052511, 2068G>C, 1G>T, 1242G>T, 2084G>A, 1780C>A}",4,5,7
51,15111599,"{279delGAG, IVS3+1G/A}",{279delGAG},1,2,1
63,15316799,"{intron2,352G>A, intron4,+718C>T, 15T>C, intron3,+45C>T}","{352G>A, +718C>T, +45C>T, 15T>C}",1,4,4
68,15481887,"{codon29,GGC>AGC, codon26,GAG>GCG}",NaN,0,2,0
69,15485686,{G>Asubstitutionatcodon1763},{G1763A},0,1,1
70,15579915,{IVS10+4G},{IVS10+4A>G},0,1,1
79,15672026,{A>Gpolymorphismatposition670},{670A>G},0,1,1
84,15768551,{GTT>GCTtransitionatcodon23},NaN,0,1,0
88,15820770,{ACG>AAGsubstitutionincodon420},NaN,0,1,0
113,16216473,"{C>TtransversionatcDNAbase463, C463T}",{C463T},1,2,1
114,16252083,"{A>Gtransitionat127position, G>Atransitionat1032position}","{G1032A, A127G}",0,2,2
121,16410744,{codon787CAG/CAA},NaN,0,1,0
130,16728705,"{C>Asubstitutionatposition863, 863C>A}",{TNFA863C>A},1,2,1
133,16822828,{TAC>AAatcodon329},"{Y329fsdeletioninsertioncombinedmutation, D487S488F489deletion, V311fs8bpnucleotidedeletion}",0,1,3
136,16843501,"{G135C, G>Ctransversionat1245position, G>Csubstitutionatposition135}",{G135C},1,3,1
141,17000021,"{+2740A>G, 1123G>C, +1858C>T}","{rs1217412, rs2488457, +1858C>T}",1,3,3
146,17059986,"{r.25212634del, 2633+1G>C}",{2633+1G>C},1,2,1
151,17166870,{6bINS},{6baseinsertioninintron7},0,1,1
171,17635946,{T>Csubstitutionatposition2209},{2209T>C},0,1,1
176,17876530,{Delta32},"{32bpdeletion, neckdomainrepeatpolymorphism8/5heterozygous}",0,1,2
180,17951029,{G>Tsubstitutionatnucleotidec.898},{898G>T},0,1,1
182,17961316,"{IVS11G>A, IVS11G>C}",{IVS11G>C},1,2,1
202,18397285,{T>Gtransversionatnucleotide4508},{T4508G},0,1,1
216,18827003,{G>Csubstitutionatposition1201},{g.1201G>C},0,1,1
219,19067809,"{A1166C, A11666C}","{A1166C, 5HTTLPR, M235T}",1,2,3
220,19082493,{ins/del6bp},"{28bpVNTR, Gallele6, deletionof6bpatposition1494, Callele6, 6+/6, C6+/6+, G6+/6+}",0,1,7
243,19559455,{Delta32},"{1088nucleotidedeletionin5'LTRgagregion, 228nucleotidedeletionin5'LTRgagregion, 13commonmutationsinconservedresidues, 247nucleotidedeletioninpolgeneuptothevifORF}",0,1,4
253,19781362,{G>Asubstitutionatnucleotide893},{893G>A},0,1,1
255,19880293,"{6054,deletion/ATT, 3279,A/C, 6054deletion/ATT, 924,A/G, IVS9+459,A/G, 924A/G}","{3279A/C, 6054deletion/ATT, IVS9+459A/G, 924A/G}",2,6,4
260,19958188,"{611T, 369C>G, AAGCat222to225, 603/604GA>AG, 588A>G, IVSII1G>A}","{611T, HS11121A, 369C>G, AAGCat222to225, 603/604GA>AG, 588A>G}",5,6,6
265,20086182,"{6526Nins/del, 6526Ndel}",{6526Ndel},1,2,1
269,20335448,{G>Aatnucleotideposition2141},{G2141A},0,1,1
281,20602574,"{G218C, T189C}","{218G/218Cand189T/189C, 218G/218C, 189T/189C}",0,2,3
296,20887110,"{C>Ttransitionatnucleotide677, 677C>T, C677T}",{C677T},1,3,1
301,21070631,{1021C/T},"{889TT, 1021T}",0,1,2
310,21135151,{delta32},NaN,0,1,0
330,21666969,{1359G/A},{1359G>A},0,1,1
353,22028770,"{+113G/C, 491AtoT, 219G/T, 491A/T}","{+113G/C, 219G/T, 491A/T}",3,4,3
361,22180037,{A>Gatnucleotide313},{A313G},0,1,1

In [46]:
merged_protein[merged_protein['Total_tmVar']>merged_protein['Matched']]

,PMID,tmVar_Mutations,cot_Mutations,Matched,Total_tmVar,Total_cot
9,12898858,{M235T},NaN,0,1,0
22,14722925,{N34S},NaN,0,1,0
23,14742428,"{S133sp, C219W, H391R, V69G, H156Y}","{C219W, H391R, V69G, H156Y, S133*}",4,5,5
26,14979495,"{R753Q, R753GLn}",NaN,0,2,0
32,15111599,{DeltaG91},{G91del},0,1,1
33,15122711,"{E873Sp, A467T}","{E873*, A467T}",1,2,2
43,15316799,{F>Satcodon15},{F15S},0,1,1
47,15485686,"{I1762A, V1763M, V1764M}",{V1763M},1,3,1
50,15623763,"{R124C, leucine269phenylalanine, valine539aspartic, arginine124cysteine, glycine594valine, H626R, L269F, V539D, histidine626arginine, V624V625del, R124L, G594V, arginine555trypphan, R555W}","{R124C, L269F, H626R, V539D, V624V625del, R124L, G594V, R555W}",8,14,8
63,15867855,{157delMTTTVP},NaN,0,1,0
66,16000134,{E272sp},{E272*},0,1,1
67,16005363,{AFF344345ins},NaN,0,1,0
74,16157158,"{C23S, C23S23}",{C23S},1,2,1
77,16181814,"{E873TAG, A467T, E873sp}","{E873*, A467T}",1,3,2
81,16252083,"{N>Ssubstitutionatcodon127, G322D, G>Dchangeatcodon322, N127S}","{N127S, G322D}",2,4,2
83,16277682,"{methionine>valinesubstitutionatcodon404, M404V}",{M404V},1,2,1
87,16419642,"{F826Y, L809L, S810L}","{F826Y, S810L}",2,3,2
89,16525586,"{Y547fs, S263F, S413L, R260H, Y69X, V414F, S290/A291fs}","{Y547fs, S263F, S413L, R260H, Y69X, S290Afs, V414F}",6,7,7
91,16601880,"{H775R, Y138F, R373W, R424X, N533Y, I440N, C644F, D880V, N732K, E270X, T187K, A841P, T830M, S957P, H651R, T269M, S132W, R461Q, R212K, G771R, R337X, R236X, R966G, G171A, E153X, V705M}","{H775R, Y138F, R373W, R424X, N533Y, I440N, C644F, N732K, E270X, T187K, T830M, H651R, T269M, S132W, R461Q, R212K, G771R, R337X, R236X, G171A, E153X, V705M}",22,26,22
94,16822828,"{Y329fs, V311fs}","{D487S488F489deletion, V311fs}",1,2,2
96,16843501,"{S326C, S>Csubstitutionatthecodon326, S1245C}",{S326C},1,3,1
131,18046082,{arginine150proline},{R150P},0,1,1
132,18050247,"{N673S, C203S}",NaN,0,2,0
142,18397285,"{L1503Q, L1503R}",{L1503R},1,2,1
151,18779591,"{I146L, I146>L}",{I146L},1,2,1
167,19429592,"{E299sp, G289sp, S522fs525sp, E169sp}","{G289*, S522fs*25, E299*, E169*}",0,4,4
192,20534762,"{C88Y, C105Vfs114X}","{C88Y, C105Vfs*114}",1,2,2
199,20801104,{1240L/S},NaN,0,1,0
202,20846357,"{A88V, D50N}",{A88V},1,2,1
207,21042587,"{R469[R,X]}",{R469*},0,1,1
214,21325775,{R158P},{P158R},0,1,1

In [28]:
# loop over the result output
i=0
for x in output_test:
    if pmid_list[i] == '21325775':
        print("="*30,pmid_list[i],"="*30)
        print(x.outputs[0].text)
        print("="*30,"="*30)
        print(tmvar_corpus[i])
    i+=1

============================== 21325775 ==============================
##APOE||-||p.Pro158Arg||Lipoprotein glomerulopathy (LPG)||nephrotic syndrome, mild dyslipidemia||conformational change of apoE protein and affects the interaction between abnormal apoE-containing lipoproteins and the endothelial cells of glomerular capillaries||likely pathogenic
============================== ==============================
Abstract: Lipoprotein glomerulopathy (LPG) is a rare disease characterized by the presence of thrombuslike deposition in markedly dilated glomerular capillaries and is often accompanied by an increased serum apolipoprotein E (apoE) level. Several gene mutations of apoE have been reported to be associated with LPG. In the current study, we report an LPG patient with a novel apoE mutation, apoE Osaka. The patient was a 45-year-old man who was hospitalized due to nephrotic syndrome. Light and electron microscopic observations of renal biopsy clearly showed characteristic findings of LPG, including lamellate thrombi in the lumen of dilated glomerular capillaries. His apoE phenotype was apoE3/2 and he had mild dyslipidemia with a mid-band on polyacrylamide gel electrophoresis. It is intriguing that the serum apoE level was within normal limits. We determined the sequence of the apoE gene using direct sequencing of the polymerase chain reaction (PCR) products. ApoE gene analysis showed a nucleotide substitution of G to C at codon 158 of exon 4. This mutation denoted an amino acid substitution of arginine residue for the proline residue at position 158 of apoE. The result of PCR associated with restriction fragment length polymorphism analysis also suggested that this mutation is heterozygous. It is possible that apoE Osaka mutation causes a conformational change of apoE protein and affects the interaction between abnormal apoE-containing lipoproteins and the endothelial cells of glomerular capillaries. The precise mechanism of LPG related with apoE Osaka, however, remains to be elucidated.

In [ ]:
tmvar_corpus[]